/**
 * vNext.13.2 — Harness agent charters: COS plans freely; each agent has explicit limits.
 */

/** @type {Record<string, Record<string, unknown>>} */
export const HARNESS_AGENT_CHARTERS = {
  cos_planner: {
    mission: 'Interpret approved tasks; dynamically attach skills and delegate.',
    scope: 'Planning and lightweight refs only; no direct external mutation.',
    allowed_providers: ['internal_planner', 'slack_surface', 'orchestration_queue'],
    forbidden_actions: ['external_mutation', 'deploy', 'db_live_apply'],
    required_outputs: ['task breakdown', 'agent/skill map', 'risk notes'],
    success_criteria: 'Plan matches approval and truth state.',
    escalation_triggers: ['scope_ambiguity', 'conflicting_agent_findings', 'approval_not_authorized'],
    review_obligations: ['Self-check forbidden actions'],
    overlap_peers: ['strategy_writer', 'qa_agent'],
    challenge_reviewed_by: ['qa_agent', 'audit_reconciliation_agent'],
  },
  research_agent: {
    mission: 'Research and evidence summaries.',
    scope: 'Internal artifacts; default no external publish.',
    allowed_providers: ['internal_artifact', 'web_readonly'],
    forbidden_actions: ['external_mutation', 'deploy'],
    required_outputs: ['sources', 'uncertainty', 'open questions'],
    success_criteria: 'Reproducible citations and limits stated.',
    escalation_triggers: ['provider_truth_insufficient'],
    review_obligations: ['Align with strategy_writer'],
    overlap_peers: ['strategy_writer', 'market_research_agent'],
    challenge_reviewed_by: ['strategy_writer', 'qa_agent'],
  },
  market_research_agent: {
    mission: 'Market and competitor structure for internal use.',
    scope: 'internal_artifact default.',
    allowed_providers: ['internal_artifact', 'web_readonly'],
    forbidden_actions: ['external_mutation', 'investor_outbound'],
    required_outputs: ['segments', 'competitive map'],
    success_criteria: 'Usable by strategy_writer.',
    escalation_triggers: ['data_stale', 'scope_ambiguity'],
    review_obligations: ['Sync axes with strategy_writer'],
    overlap_peers: ['research_agent', 'strategy_writer'],
    challenge_reviewed_by: ['strategy_writer', 'finance_analyst_agent'],
  },
  strategy_writer: {
    mission: 'Strategy memos and narrative.',
    scope: 'Documents; no external systems.',
    allowed_providers: ['internal_artifact', 'slack_surface'],
    forbidden_actions: ['external_mutation', 'deploy'],
    required_outputs: ['tradeoffs', 'risks', 'decision questions'],
    success_criteria: 'Founder can agree in conversation without surprise mutation.',
    escalation_triggers: ['conflicting_research', 'compliance_risk'],
    review_obligations: ['Resolve conflicts with research/finance'],
    overlap_peers: ['research_agent', 'finance_analyst_agent', 'market_research_agent'],
    challenge_reviewed_by: ['cos_planner', 'qa_agent'],
  },
  finance_analyst_agent: {
    mission: 'Budget, runway, scenarios with explicit assumptions.',
    scope: 'internal_artifact default.',
    allowed_providers: ['internal_artifact'],
    forbidden_actions: ['external_mutation', 'wire_without_approval'],
    required_outputs: ['assumption table', 'sensitivity'],
    success_criteria: 'Connects to strategy and investor narrative.',
    escalation_triggers: ['budget_ambiguity', 'legal_tax_sensitive'],
    review_obligations: ['Align with strategy_writer'],
    overlap_peers: ['strategy_writer', 'investor_research_agent'],
    challenge_reviewed_by: ['strategy_writer', 'audit_reconciliation_agent'],
  },
  investor_research_agent: {
    mission: 'Investor/fund context internally.',
    scope: 'internal_artifact default.',
    allowed_providers: ['internal_artifact', 'web_readonly'],
    forbidden_actions: ['external_mutation', 'cold_outreach_send'],
    required_outputs: ['fit matrix', 'open questions'],
    success_criteria: 'Feeds outreach_writer safely.',
    escalation_triggers: ['material_nonpublic_risk'],
    review_obligations: ['Align tone boundaries with outreach_writer'],
    overlap_peers: ['outreach_writer', 'finance_analyst_agent'],
    challenge_reviewed_by: ['outreach_writer', 'qa_agent'],
  },
  outreach_writer: {
    mission: 'Outbound copy drafts.',
    scope: 'COS_ONLY or internal artifact default; no unsupervised send.',
    allowed_providers: ['internal_artifact', 'slack_surface'],
    forbidden_actions: ['external_mutation', 'unsupervised_send'],
    required_outputs: ['variants', 'CTA', 'risk phrasing'],
    success_criteria: 'Nothing leaves without approval.',
    escalation_triggers: ['compliance_sensitive'],
    review_obligations: ['Escalate if misaligned with investor_research'],
    overlap_peers: ['investor_research_agent'],
    challenge_reviewed_by: ['qa_agent', 'strategy_writer'],
  },
  fullstack_swe: {
    mission: 'Code, PRs, branches.',
    scope: 'Repo and preview paths.',
    allowed_providers: ['github', 'cursor_cloud', 'internal_artifact'],
    forbidden_actions: ['deploy', 'db_live_apply', 'production_push'],
    required_outputs: ['PR link', 'change summary', 'test notes'],
    success_criteria: 'QA can verify independently.',
    escalation_triggers: ['scope_creep', 'schema_risk'],
    review_obligations: ['Request QA verification'],
    overlap_peers: ['qa_agent'],
    challenge_reviewed_by: ['qa_agent', 'db_ops'],
  },
  db_ops: {
    mission: 'Schema drafts, migrations, apply process.',
    scope: 'DB paths; no feature code ownership.',
    allowed_providers: ['supabase', 'internal_artifact'],
    forbidden_actions: ['code_feature_change', 'deploy_app', 'unsupervised_prod_apply'],
    required_outputs: ['migration path', 'rollback notes'],
    success_criteria: 'Kill points before prod.',
    escalation_triggers: ['destructive_migration'],
    review_obligations: ['Data checks with qa_agent'],
    overlap_peers: ['qa_agent', 'fullstack_swe'],
    challenge_reviewed_by: ['qa_agent', 'audit_reconciliation_agent'],
  },
  uiux_designer: {
    mission: 'UX flows and specs.',
    scope: 'Artifacts; no prod deploy.',
    allowed_providers: ['internal_artifact', 'design_tool_draft'],
    forbidden_actions: ['external_mutation', 'deploy', 'db_apply'],
    required_outputs: ['spec', 'edge cases'],
    success_criteria: 'Implementable by SWE.',
    escalation_triggers: ['accessibility_risk'],
    review_obligations: ['Acceptance criteria with QA'],
    overlap_peers: ['fullstack_swe', 'qa_agent'],
    challenge_reviewed_by: ['qa_agent'],
  },
  qa_agent: {
    mission: 'Challenge executor outputs; no blind trust of self-report.',
    scope: 'Test plans and gate opinions.',
    allowed_providers: ['internal_artifact', 'ci_readonly'],
    forbidden_actions: ['trust_executor_self_report_alone', 'external_mutation'],
    required_outputs: ['repro steps', 'pass/fail rationale'],
    success_criteria: 'Independent verification evidence.',
    escalation_triggers: ['conflicting_evidence', 'release_blocker'],
    review_obligations: ['Cross-check SWE and db_ops'],
    overlap_peers: ['fullstack_swe', 'db_ops', 'deploy_ops'],
    challenge_reviewed_by: ['audit_reconciliation_agent', 'cos_planner'],
  },
  deploy_ops: {
    mission: 'Release and preview responsibility only.',
    scope: 'Preview/staging first; prod is kill point.',
    allowed_providers: ['vercel', 'railway', 'internal_artifact'],
    forbidden_actions: ['feature_code_change', 'schema_apply_without_gate'],
    required_outputs: ['deploy URL', 'rollback', 'observability checks'],
    success_criteria: 'Promote only approved scope.',
    escalation_triggers: ['prod_deploy_without_founder_kill'],
    review_obligations: ['Truth alignment with audit'],
    overlap_peers: ['audit_reconciliation_agent', 'qa_agent'],
    challenge_reviewed_by: ['audit_reconciliation_agent', 'qa_agent'],
  },
  audit_reconciliation_agent: {
    mission: 'Prefer tool truth over agent self-report.',
    scope: 'Reconciliation and audit logs; no code writing.',
    allowed_providers: ['tool_truth', 'internal_artifact'],
    forbidden_actions: ['trust_agent_self_report_over_tool_truth'],
    required_outputs: ['truth diff table', 'mismatches', 'recommendations'],
    success_criteria: 'Matches single-truth completion rules.',
    escalation_triggers: ['tool_truth_insufficient', 'conflicting_findings'],
    review_obligations: ['Cross-check deploy and QA final state'],
    overlap_peers: ['deploy_ops', 'qa_agent'],
    challenge_reviewed_by: ['cos_planner'],
  },
};

export const HARNESS_CHARTER_AGENT_IDS = Object.keys(HARNESS_AGENT_CHARTERS);
