-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnjv9lim-ka7ht
-- packet_id: EPK-mnjv9lim-68bsb
-- schema_draft_json: data/supabase-drafts/supabase_draft_task_RUN-mnjv9lim-ka7ht.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
