-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnjj92kf-fk301
-- packet_id: EPK-mnjj92kf-4f11x
-- schema_draft_json: data/supabase-drafts/supabase_draft_calendar-tool_RUN-mnjj92kf-fk301.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
