-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnj6prxa-d8qv6
-- packet_id: EPK-mnj6prxa-eism9
-- schema_draft_json: data/supabase-drafts/supabase_draft_calendar-tool_RUN-mnj6prxa-d8qv6.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
