-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnjj8594-0gcoo
-- packet_id: EPK-mnjj8594-qo2ar
-- schema_draft_json: data/supabase-drafts/supabase_draft_task_RUN-mnjj8594-0gcoo.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
