-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnlja383-bpkq9
-- packet_id: EPK-mnlja383-zjmwq
-- schema_draft_json: data/supabase-drafts/supabase_draft_task_RUN-mnlja383-bpkq9.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
