-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnjvg847-5aqui
-- packet_id: EPK-mnjvg847-rehes
-- schema_draft_json: data/supabase-drafts/supabase_draft_task_RUN-mnjvg847-5aqui.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
