-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnlhab3v-c4ks7
-- packet_id: EPK-mnlhab3v-ellg9
-- schema_draft_json: data/supabase-drafts/supabase_draft_calendar-tool_RUN-mnlhab3v-c4ks7.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
