-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnmhoyjd-vev2s
-- packet_id: EPK-mnmhoyjd-75y2t
-- schema_draft_json: data/supabase-drafts/supabase_draft_task_RUN-mnmhoyjd-vev2s.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
