-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnms8vd5-ef4a7
-- packet_id: EPK-mnms8vd5-2ia8i
-- schema_draft_json: data/supabase-drafts/supabase_draft_task_RUN-mnms8vd5-ef4a7.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
