-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnjgoajh-2jaxt
-- packet_id: EPK-mnjgoajh-xqwpd
-- schema_draft_json: data/supabase-drafts/supabase_draft_task_RUN-mnjgoajh-2jaxt.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
