-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnlehk2g-pj31c
-- packet_id: EPK-mnlehk2g-dats9
-- schema_draft_json: data/supabase-drafts/supabase_draft_calendar-tool_RUN-mnlehk2g-pj31c.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
