-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnj37lly-ycz4z
-- packet_id: EPK-mnj37lly-f1nf5
-- schema_draft_json: data/supabase-drafts/supabase_draft_calendar-tool_RUN-mnj37lly-ycz4z.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
