-- COS auto-generated migration stub (comments only; no DDL executed by COS).
-- run_id: RUN-mnj4vjyy-q6ir8
-- packet_id: EPK-mnj4vjyy-y06zs
-- schema_draft_json: data/supabase-drafts/supabase_draft_task_RUN-mnj4vjyy-q6ir8.json
-- Replace with real DDL; apply via Supabase CLI to staging before production.
